name: Brian Moore
author: Brian Moore
url: https://brianmoore.com/
shareimage: /static/img/brian-share.jpg
sitedescription: Brian Moore plays with technology to create art and products
  that comment on popular culture, society, and technology itself.
baseurl: https://ecstatic-dubinsky-bfec92.netlify.app
