name: Brian Moore
author: Brian Moore
url: https://brianmoore.com/
shareimage: /static/img/brian.png
sitedescription: Brian Moore plays with technology to create art and products
  that comment on popular culture, society, and technology itself.
