backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Work"
    name: "work"
    folder: "src/work"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subhead", name: "subhead", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "code", default_language: "html" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Contact"
        name: "contact"
        file: "src/_data/contact.yaml"
        fields:
          - label: Contact Links
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Press"
        name: "press"
        file: "src/_data/press.yaml"
        fields:
          - { label: Publication, name: publication, widget: string }
          - { label: Subhead, name: subhead, widget: string }
          - { label: URL, name: url, widget: string }
      - label: "Awards"
        name: "awards"
        file: "src/_data/awards.yaml"
        fields:
          - { label: Award, name: award, widget: string }
          - { label: Subhead, name: subhead, widget: string }
          - { label: URL, name: url, widget: string, required: false}
      - label: "Speaking"
        name: "speaking"
        file: "src/_data/speaking.yaml"
        fields:
          - { label: Event, name: event, widget: string }
          - { label: Subhead, name: subhead, widget: string }
          - { label: URL, name: url, widget: string, required: false}
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
